### ISSUE TITLE
gradle not found when trying to generate model files

### ISSUE THREAD

**Issue by j4nos** [dkharrat/NexusData#10]
Where should I put in the following command on a Mac, in terminal? Gradle shuld be preinstalled on my Mac?

gradle :modelgen:run -Pargs="-f /path/to/model/todo.model.json -O /path/to/output/src/main/java"

I do not see gradle script in the project folder.

Kukodas-MacBook-Air:MovieBuffs3 kukodajanos$ ls
MovieBuffs3.iml     gradle          local.properties
app         gradle.properties   settings.gradle
build           gradlew
build.gradle        gradlew.bat
Kukodas-MacBook-Air:MovieBuffs3 kukodajanos$ gradle
-bash: gradle: command not found

**Comment by dkharrat** [comment]
Looks like you don't have gradle installed in your system. You can use the provided gradle script (gradlew in the root of the project) instead:

    ./gradlew :modelgen:run -Pargs="-f /path/to/model/todo.model.json -O /path/to/output/src/main/java"

I'll need to update the README file to reference the provided gradle script, since it's safer.

**Comment by j4nos** [comment]
Hi! Tried your script, it started, but at the end I get following error message. Do you have any idea, what cause it?

Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Project 'modelgen' not found in root project 'MovieBuffs3'.
