### ISSUE TITLE
Support to configure Parent Entity

### ISSUE THREAD

**Issue by karthik1729** [dkharrat/NexusData#7]

**Comment by malcolmhall** [comment]
I thought I'd chip in that he is talking about entity inheritance. E.g.g a child entity inherits the attributes of a parent one, essentially like subclassing. Although Apple Core Data provides this feature once you learn how it is implemented most are less inclined to make use of it. Core Data stores all entities with the same parent entity in the same table, so you have one huge table with many unused columns.

**Comment by dkharrat** [comment]
Thanks for the clarification. Makes sense now. There's no direct support for entity inheritance yet. I'll leave this ticket open until it's implemented.

Using multiple columns to support entity inheritance is a pretty standard approach to implement it. If anyone has a better approach, I'd be happy to hear it.

**Comment by dkharrat** [comment]
This is now supported in 0.2.1.
