### ISSUE TITLE
Where is pom.xml located?

### ISSUE THREAD

**Issue by j4nos** [dkharrat/NexusData#9]
I am a bit newbie in Android development. Have more experience in iOS development. Have a Mac and Android Studio. How can I 'Add the following dependency to your pom.xml file for your project:' ?I do not find pom.xml in my project I just created. Do I have to install first Maven? Or is it coming with Android Studio?

**Comment by dkharrat** [comment]
This project does not use maven; it uses gradle instead, which is what Android Studio supports. You just have to add the NexusData dependency in your build.gradle file. If you are using maven, add the dependency to your pom.xml. Instructions are in the README file. Also, take a look at the sample project for an example.
